name: Write Status PR Comment
description: Write a comment to a pull request based on the status of another job

inputs:
  caller_job_name:
    description: The name of the job that calls this one
    required: true
  github_token:
    description: The GitHub token to authenticate with
    required: true
  message_failure:
    description: The failure message to use
    required: true
  message_success:
    description: The success message to use
    required: true
  status:
    description: The status to report on (either 'success' or 'failure')
    required: true

runs:
  using: composite
  steps:
    - id: job_log_url
      uses: Tiryoh/gha-jobid-action@v0
      with:
        github_token: ${{ inputs.github_token }}
        job_name: ${{ inputs.caller_job_name }} / ${{ github.job }}

    - if: ${{ inputs.status }} == 'failure'
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: execution
        message: ${{ inputs.message_failure }} ${{ steps.job_log_url.outputs.html_url }}

    - if: ${{ inputs.status }} == 'success'
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: execution
        message: ${{ inputs.message_success }} ${{ steps.job_log_url.outputs.html_url }}
