name: Deploy Site
description: Deploy HTML static files to a GitHub branch

inputs:
  private_deploy_key:
    description: This should be set in the GitHub repository settings if deploying to external repository
    required: false
  source_folder:
    description: The folder to deploy from with a / at the end
    required: true
  target_branch:
    description: The branch to deploy to
    required: true
  target_external_repository:
    description: Whether to deploy to an external repository or not
    required: true
  target_repository_name:
    description: The repository to deploy to
    required: true

runs:
  using: composite
  steps:
    - if: ${{ inputs.target_external_repository }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: ${{ inputs.target_branch }}
        clean: true
        commit-message: Deploy to ${{ inputs.target_repository_name }}
        folder: ${{ inputs.source_folder }}
        git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
        git-config-name: github-actions[bot]
        repository-name: ${{ inputs.target_repository_name }}
        silent: true
        ssh-key: ${{ inputs.private_deploy_key }}

    - if: ${{ inputs.target_external_repository == false }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: ${{ inputs.target_branch }}
        clean: true
        commit-message: Deploy to ${{ inputs.target_repository_name }}
        folder: ${{ inputs.source_folder }}
        git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
        git-config-name: github-actions[bot]
        silent: true
