name: Javascript Linter
description: Lint JS files

inputs:
  linter_command:
    description: The file or command to run
    required: true
  node_version:
    default: 18
    description: The Node version to use
    required: false

runs:
  using: composite
  steps:
    - id: set-branch-variable
      uses: emmahsax/reusable-github-actions-workflows/set-branch-variable@test

    - uses: actions/checkout@v3
      with:
        ref: ${{ steps.set-branch-variable.outputs.branch }}

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: https://registry.npmjs.org

    - run: npm install standard --save-dev && ${{ inputs.linter_command }}
