name: GitLeaks

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: GitLeaks
        uses: emmahsax/reusable-github-actions-workflows/gitleaks@test
