on:
  workflow_call:
    inputs:
      build_command:
        required: true
        type: string
      files:
        default: ""
        description: A newline-delimited glob of paths to assets to upload
        required: false
        type: string
      go_version:
        default: 1.21
        description: The version of Go to build
        required: false
        type: number
      tag_name:
        description: The name of the tag/release to use
        required: false
        type: string
      upload:
        description: Whether to upload assets during the release
        required: true
        type: boolean

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Go
        uses: emmahsax/github-actions/setup-go@main
        with:
          github_token: ${{ secrets.github_token }}
          go_version: ${{ inputs.go_version }}

      - name: Go Build
        run: ${{ inputs.build_command }}

      - name: Set Tag Name
        id: tag_name
        run: |
          if [[ ${{ inputs.tag_name }} == '' ]]; then
            CALCULATED_SHA=$(git rev-parse --short ${{ github.sha }})
            echo "tag_name=$CALCULATED_SHA" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${{ inputs.tag_name }}" >> $GITHUB_OUTPUT
          fi

      - if: ${{ inputs.upload }}
        name: GitHub Release & Upload Assets
        uses: softprops/action-gh-release@v1
        env:
          github_token: ${{ secrets.github_token }}
        with:
          draft: false
          files: ${{ inputs.files }}
          name: ${{ steps.tag_name.outputs.tag_name }}
          prerelease: false
          tag_name: ${{ steps.tag_name.outputs.tag_name }}

      - if: ${{ inputs.upload == false }}
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          github_token: ${{ secrets.github_token }}
        with:
          draft: false
          name: ${{ steps.tag_name.outputs.tag_name }}
          prerelease: false
          tag_name: ${{ steps.tag_name.outputs.tag_name }}
