on:
  workflow_call:
    inputs:
      branch:
        description: The branch to check out
        required: true
        type: string
      build_command:
        default: go build -v ./...
        required: false
        type: string
      go_version:
        default: 1.22
        description: The version of Go to build
        required: false
        type: number
      staticcheck:
        default: true
        description: Whether to run staticcheck or not
        required: false
        type: boolean
      test_command:
        default: go test -v ./...
        required: false
        type: string
      vet_command:
        default: go vet -v ./...
        required: false
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Go
        uses: emmahsax/github-actions/setup-go@main
        with:
          github_token: ${{ secrets.github_token }}
          go_version: ${{ inputs.go_version }}

      - name: Go Build
        run: ${{ inputs.build_command }}

      - name: Go Test
        run: ${{ inputs.test_command }}

      - name: Go Vet
        run: ${{ inputs.vet_command }}

      - name: Go FMT
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: ./
          gofmt-flags: '-l -d'

      - if: ${{ inputs.staticcheck }}
        name: Go Staticcheck
        uses: dominikh/staticcheck-action@main
        with:
          install-go: true
          cache-key: ${{ inputs.go_version }}
          working-directory: ./
