on:
  workflow_call:
    inputs:
      hugo_version:
        default: '0.145.0'
        description: The Hugo version to use
        required: false
        type: string
      target_branch:
        default: pages
        description: The branch to deploy to
        required: false
        type: string
      target_external_repository:
        default: false
        description: Whether to deploy to an external repository or not
        required: false
        type: boolean
      target_repository_name:
        description: The repository to deploy to if not the same repository
        required: false
        type: string
    secrets:
      private_deploy_key:
        description: This should be set in the GitHub repository settings if deploying to external repository
        required: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2147483647
          ref: main

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ inputs.hugo_version }}
          extended: true

      - name: Hugo Build
        run: HUGO_ENV=production hugo

      - if: ${{ inputs.target_external_repository }}
        name: Deploy Site to External Repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ inputs.target_branch }}
          clean: true
          commit-message: Deploy to ${{ inputs.target_repository_name }}
          folder: public/
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          git-config-name: github-actions[bot]
          repository-name: ${{ inputs.target_repository_name }}
          silent: true
          ssh-key: ${{ secrets.private_deploy_key }}

      - if: ${{ inputs.target_external_repository == false }}
        name: Deploy Site to Internal Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ inputs.target_branch }}
          clean: true
          commit-message: Deploy to ${{ github.repository }}
          folder: public/
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          git-config-name: github-actions[bot]
          silent: true
