on:
  workflow_call:
    inputs:
      branch:
        description: The branch to check out
        required: true
        type: string
      caller_job_name:
        default: html-proofer
        description: The name of the job that calls this one
        required: false
        type: string
      command:
        description: The file or command to run
        required: true
        type: string
      html_proofer_version:
        default: '5.0'
        description: The HTML Proofer version to use
        required: false
        type: string
      hugo_version:
        default: '0.145.0'
        description: The Hugo version to use
        required: false
        type: string
      notify_pr:
        default: false
        description: Whether to notify the PR about failures/success runs
        required: false
        type: string
      ruby_version:
        default: '3'
        description: The Ruby version to use
        required: false
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ inputs.hugo_version }}
          extended: true

      - name: Hugo Build
        run: HUGO_ENV=production hugo

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby_version }}
          bundler-cache: false

      - name: Create Gemfile and Install HTML Proofer
        run: |
          echo "source 'https://rubygems.org'" > Gemfile
          echo "gem 'html-proofer', '~> ${{ inputs.html_proofer_version }}'" >> Gemfile
          bundle install

      - name: HTML Proofer
        run: |
          if ${{ inputs.notify_pr }}; then
            if ${{ inputs.command }}; then
              echo "status=success" >> $GITHUB_ENV
            else
              echo "status=fail" >> $GITHUB_ENV
            fi
          else
            ${{ inputs.command }}
          fi

      - id: job_log_url
        if: github.event_name == 'pull_request' && inputs.notify_pr == 'true'
        name: Get Job Log URL
        uses: Tiryoh/gha-jobid-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          job_name: ${{ inputs.caller_job_name }} / ${{ github.job }}

      - if: github.event_name == 'pull_request' && inputs.notify_pr == 'true' && env.status == 'fail'
        name: Pull Request Failure Comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: html-proofer
          message: |
            :warning: Latest run of Hugo Site HTML Proofer **failed**: ${{ steps.job_log_url.outputs.html_url }}

      - if: github.event_name == 'pull_request' && inputs.notify_pr == 'true' && env.status == 'success'
        name: Pull Request Success Comment
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: html-proofer
          message: |
            :white_check_mark: Latest run of Hugo Site HTML Proofer **succeeded**: ${{ steps.job_log_url.outputs.html_url }}
