on:
  workflow_call:
    inputs:
      branch:
        description: The branch to check out
        required: true
        type: string
      command:
        description: The file or command to run
        required: false
        type: string
      linter_command:
        description: The file or command to run
        required: false
        type: string
      node_version:
        default: 20
        description: The Node version to use
        required: false
        type: number

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          registry-url: https://registry.npmjs.org

      - name: Javascript Linter
        run: npm install standard --save-dev && ${{ inputs.linter_command || inputs.command }}
