on:
  workflow_call:
    inputs:
      branch:
        description: The branch to check out
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Jekyll Build
        run: JEKYLL_ENV=production bundle exec jekyll build --destination _site/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: _site/
