on:
  workflow_call:
    inputs:
      move_static_files:
        default: true
        description: Whether to move the source_folder/source_static_folder/* to source_folder/*
        required: false
        type: boolean
      source_folder:
        default: _site/
        description: The folder to deploy from with a / at the end
        required: false
        type: string
      source_static_folder:
        default: site_files/ # TODO: Change to static/
        description: The location of the static files with a / at the end
        required: false
        type: string
      target_branch:
        default: pages
        description: The branch to deploy to
        required: false
        type: string
      target_external_repository:
        default: false
        description: Whether to deploy to an external repository or not
        required: false
        type: boolean
      target_repository_name:
        description: The repository to deploy to if not the same repository
        required: false
        type: string
    secrets:
      private_deploy_key:
        description: This should be set in the GitHub repository settings if deploying to external repository
        required: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2147483647
          ref: main

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Jekyll Build
        run: JEKYLL_ENV=production bundle exec jekyll build --destination ${{ inputs.source_folder }}

      - if: ${{ inputs.move_static_files }}
        name: Move Static Files
        run: |
          rsync -a --remove-source-files ${{ inputs.source_static_folder }} ${{ inputs.source_folder }}
          rm -r ${{ inputs.source_folder }}${{ inputs.source_static_folder }} || echo 0

      - if: ${{ inputs.target_external_repository }}
        name: Deploy Site to External Repository
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ inputs.target_branch }}
          clean: true
          commit-message: Deploy to ${{ inputs.target_repository_name }}
          folder: ${{ inputs.source_folder }}
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          git-config-name: github-actions[bot]
          repository-name: ${{ inputs.target_repository_name }}
          silent: true
          ssh-key: ${{ secrets.private_deploy_key }}

      - if: ${{ inputs.target_external_repository == false }}
        name: Deploy Site to Internal Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ inputs.target_branch }}
          clean: true
          commit-message: Deploy to ${{ github.repository }}
          folder: ${{ inputs.source_folder }}
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          git-config-name: github-actions[bot]
          silent: true
