on:
  workflow_call:
    inputs:
      move_site_files:
        default: true
        description: Whether to move the source_folder/source_site_files_folder/* to source_folder/*
        required: false
        type: boolean
      source_folder:
        default: _site/
        description: The folder to deploy from with a / at the end
        required: false
        type: string
      source_site_files_folder:
        default: site_files/
        description: The location of the site files with a / at the end
        required: false
        type: string
      target_branch:
        default: pages
        description: The branch to deploy to
        required: false
        type: string
      target_external_repository:
        default: false
        description: Whether to deploy to an external repository or not
        required: false
        type: boolean
      target_repository_name:
        description: The repository to deploy to if not the same repository
        required: false
        type: string
    secrets:
      private_deploy_key:
        description: This should be set in the GitHub repository settings if deploying to external repository
        required: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2147483647
          ref: main

      - name: Install Ruby and Bundle Install
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Jekyll Build
        uses: emmahsax/github-actions/jekyll-build@test_composite
        with:
          target_dir: ${{ inputs.source_folder }}

      - if: ${{ inputs.move_site_files }}
        name: Move Site Files
        uses: emmahsax/github-actions/move-up-nested-files@main
        with:
          dir: ${{ inputs.source_folder }}
          nested_dir: ${{ inputs.source_site_files_folder }}

      - name: Deploy Site
        uses: emmahsax/github-actions/deploy-site@test_composite
        with:
          private_deploy_key: ${{ secrets.private_deploy_key }}
          source_folder: ${{ inputs.source_folder }}
          target_branch: ${{ inputs.target_branch }}
          target_external_repository: ${{ inputs.target_external_repository }}
          target_repository_name: ${{ inputs.target_repository_name }}
