on:
  workflow_call:
    inputs:
      caller_job_name:
        default: jekyll-site-html-proofer
        description: The name of the job that calls this one
        required: false
        type: string
      command:
        description: The file or command to run
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - id: set_branch_variable
        name: Set Branch Variable
        uses: emmahsax/github-actions/set-branch-variable@main

      - name: Check Out Code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.set_branch_variable.outputs.branch }}

      - name: Install Ruby and Bundle Install
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Jekyll Build
        uses: emmahsax/github-actions/jekyll-build@test_composite

      - name: HTML Proofer
        run: |
          if ${{ inputs.command }}; then
            echo "proofer_status=success" >> $GITHUB_ENV
          else
            echo "proofer_status=failure" >> $GITHUB_ENV
          fi

      - if: github.event_name == 'pull_request'
        name: Write Status PR Comment
        uses: emmahsax/github-actions/write-status-pr-comment@test_composite
        with:
          caller_job_name: ${{ inputs.caller_job_name }}
          github_token: ${{ secrets.github_token }}
          message_failure: ":warning: Latest run of Jekyll Site HTML Proofer **failed**:"
          message_success: ":white_check_mark: Latest run of Jekyll Site HTML Proofer **succeeded**:"
          status: ${{ env.proofer_status }}
