on:
  workflow_call:
    inputs:
      # The file or command to run
      LINTER_COMMAND:
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Variable
        run: |
          if [[ ${{ github.REF }} == 'refs/heads'* ]]; then # This is a branch, not a pull request
            echo "BRANCH=$(echo ${{ github.REF }} | sed -E 's|refs/[a-zA-Z]+/||')" >> $GITHUB_ENV
          else
            echo "BRANCH=$(echo ${{ github.HEAD_REF }} | sed -E 's|refs/[a-zA-Z]+/||')" >> $GITHUB_ENV
          fi
      - name: Check Out Code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
      - name: Install Ruby and Bundle Install
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Markdown Linter
        run: ${{ inputs.LINTER_COMMAND }}
