name: GitLeaks

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gitleaks:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ./.github/workflows/gitleaks.yml
