on:
  workflow_call:
    inputs:
      branch:
        description: The branch to check out
        required: true
        type: string
      terraform_version:
        default: '~1.15.8'
        description: The Terraform version to use
        required: false
        type: string
      working_directories:
        default: '["."]'
        description: JSON-encoded list of working directories to run Terraform commands in
        required: false
        type: string

jobs:
  main:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        working_directory: ${{ fromJSON(inputs.working_directories) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Format Check
        run: terraform fmt -check -diff
        working-directory: ${{ matrix.working_directory }}

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ${{ matrix.working_directory }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ matrix.working_directory }}
